export interface Boss {
  name: string
  defeated: boolean
}

export interface Area {
  location: string
  bosses: Boss[]
}

export const Areas: Area[] = [
  {
    location: 'Abyssal Woods',
    bosses: [{ name: 'Midra Lord of Frenzied Flame', defeated: false }],
  },
  {
    location: 'Ainsel River',
    bosses: [{ name: 'Dragonkin Soldier of Nokstella', defeated: false }],
  },
  {
    location: 'Altus Plateau',
    bosses: [
      { name: 'Ancient Dragon Lansseax', defeated: false },
      { name: 'Ancient Hero of Zamor', defeated: false },
      { name: "Black Knife Assassin (Sage's Cave)", defeated: false },
      { name: "Black Knife Assassin (Sainted Hero's Grave)", defeated: false },
      { name: 'Crystalian Spear & Crystalian Ringblade', defeated: false },
      { name: 'Demi-Human Queen Gilika', defeated: false },
      { name: 'Elemer of the Briar', defeated: false },
      { name: 'Erdtree Burial Watchdog', defeated: false },
      { name: 'Fallingstar Beast', defeated: false },
      { name: 'Godefroy The Grafted', defeated: false },
      { name: 'Godskin Apostle', defeated: false },
      { name: 'Necromancer Garris', defeated: false },
      { name: "Night's Cavalry", defeated: false },
      { name: 'Omenkiller & Miranda the Blighted Bloom', defeated: false },
      { name: 'Perfumer Tricia & Misbegotten Warrior', defeated: false },
      { name: 'Sanguine Noble', defeated: false },
      { name: 'Stonedigger Troll', defeated: false },
      { name: 'Tibia Mariner', defeated: false },
      { name: 'Tree Sentinel (Duo)', defeated: false },
      { name: 'Wormface', defeated: false },
    ],
  },
  {
    location: 'Ancient Ruins of Rauh',
    bosses: [
      { name: 'Divine Beast Dancing Lion', defeated: false },
      { name: 'Romina, Saint of the Bud', defeated: false },
    ],
  },
  {
    location: 'Caelid',
    bosses: [
      { name: 'Cemetery Shade', defeated: false },
      { name: "Commander O'Neil", defeated: false },
      { name: 'Crucible Knight & Misbegotten Warrior', defeated: false },
      { name: 'Death Rite Bird', defeated: false },
      { name: 'Decaying Ekzykes', defeated: false },
      { name: 'Erdtree Burial Watchdog (Duo)', defeated: false },
      { name: 'Fallingstar Beast', defeated: false },
      { name: 'Frenzied Duelist', defeated: false },
      { name: 'Mad Pumpkin Heads', defeated: false },
      { name: 'Magma Wyrm', defeated: false },
      { name: "Night's Cavalry (Caelid)", defeated: false },
      { name: 'Nox Swordstress & Nox Priest', defeated: false },
      { name: 'Putrid Avatar', defeated: false },
      { name: 'Starscourge Radahn', defeated: false },
    ],
  },
  {
    location: 'Capital Outskirts',
    bosses: [
      { name: 'Bell Bearing Hunter', defeated: false },
      { name: 'Crucible Knight & Crucible Knight Ordovis', defeated: false },
      { name: 'Deathbird', defeated: false },
      { name: 'Draconic Tree Sentinel', defeated: false },
      { name: 'Fell Twins', defeated: false },
      { name: 'Grave Warden Duelist', defeated: false },
      { name: 'Onyx Lord', defeated: false },
    ],
  },
  {
    location: 'Cerulean Coast',
    bosses: [
      { name: 'Dancer of Ranah', defeated: false },
      { name: 'Demi-Human Queen Marigga', defeated: false },
      { name: 'Ghostflame Dragon', defeated: false },
      { name: 'Putrescent Knight', defeated: false },
    ],
  },
  {
    location: "Charo's Hidden Grave",
    bosses: [
      { name: 'Death Rite Bird', defeated: false },
      { name: 'Lamenter', defeated: false },
      { name: 'Tibia Mariner', defeated: false },
    ],
  },
  {
    location: 'Consecrated Snowfield',
    bosses: [
      { name: 'Astel, Stars of Darkness', defeated: false },
      { name: 'Death Rite Bird', defeated: false },
      { name: 'Great Wyrm Theodorix', defeated: false },
      { name: 'Misbegotten Crusader', defeated: false },
      { name: "Night's Cavalry (Duo)", defeated: false },
      { name: 'Putrid Avatar', defeated: false },
      { name: 'Putrid Grave Warden Duelist', defeated: false },
    ],
  },
  {
    location: 'Crumbling Farum Azula',
    bosses: [
      { name: 'Beast Clergyman / Maliketh, the Black Blade', defeated: false },
      { name: 'Dragonlord Placidusax', defeated: false },
      { name: 'Godskin Duo', defeated: false },
    ],
  },
  {
    location: 'Deeproot Depths',
    bosses: [
      { name: 'Crucible Knight Siluria', defeated: false },
      { name: "Fia's Champions", defeated: false },
      { name: 'Lichdragon Fortissax', defeated: false },
    ],
  },
  {
    location: 'Dragonbarrow',
    bosses: [
      { name: 'Battlemage Hugues', defeated: false },
      { name: 'Beastman of Farum Azula (Duo)', defeated: false },
      { name: 'Bell Bearing Hunter', defeated: false },
      { name: 'Black Blade Kindred ', defeated: false },
      { name: 'Cleanrot Knight (Duo)', defeated: false },
      { name: 'Flying Dragon Greyll', defeated: false },
      { name: 'Godskin Apostle', defeated: false },
      { name: "Night's Cavalry (Dragonbarrow)", defeated: false },
      { name: 'Putrid Avatar', defeated: false },
      { name: 'Putrid Crystalian Trio', defeated: false },
      { name: 'Putrid Tree Spirit', defeated: false },
    ],
  },
  {
    location: 'Elden Throne',
    bosses: [{ name: 'Radagon of the Golden Order / Elden Beast', defeated: false }],
  },
  {
    location: 'Enir-Ilim',
    bosses: [{ name: 'Promised Consort Radahn + Radahn Consort of Miquella', defeated: false }],
  },
  {
    location: 'Forbidden Lands',
    bosses: [
      { name: 'Black Blade Kindred', defeated: false },
      { name: "Night's Cavalry", defeated: false },
      { name: 'Stray Mimic Tear', defeated: false },
    ],
  },
  {
    location: 'Gravesite Plain',
    bosses: [
      { name: 'Blackgaol Knight', defeated: false },
      { name: 'Chief Bloodfiend', defeated: false },
      { name: 'Demi-Human Swordmaster Onze', defeated: false },
      { name: 'Divine Beast Dancing Lion', defeated: false },
      { name: 'Ghostflame Dragon', defeated: false },
      { name: 'Rellana Twin Moon Knight', defeated: false },
      { name: 'Red Bear', defeated: false },
    ],
  },
  {
    location: 'Jagged Peak',
    bosses: [
      { name: 'Ancient Dragon-Man', defeated: false },
      { name: 'Ancient Dragon Senessax', defeated: false },
      { name: 'Bayle the Dread', defeated: false },
      { name: 'Jagged Peak Drake x2', defeated: false },
    ],
  },
  {
    location: 'Lake of Rot',
    bosses: [
      { name: 'Astel, Naturalborn of the Void', defeated: false },
      { name: 'Dragonkin Soldier', defeated: false },
    ],
  },
  {
    location: 'Leyndell, Ashen Capital',
    bosses: [
      { name: 'Godfrey, First Elden Lord (Hoarah Loux)', defeated: false },
      { name: 'Sir Gideon Ofnir, the All-Knowing', defeated: false },
    ],
  },
  {
    location: 'Leyndell, Royal Capital',
    bosses: [
      { name: 'Esgar, Priest of Blood', defeated: false },
      { name: 'Godfrey, First Elden Lord', defeated: false },
      { name: 'Mohg, the Omen', defeated: false },
      { name: 'Morgott, the Omen King', defeated: false },
    ],
  },
  {
    location: 'Limgrave',
    bosses: [
      { name: 'Beastman of Farum Azula', defeated: false },
      { name: 'Bell Bearing Hunter', defeated: false },
      { name: 'Black Knife Assassin', defeated: false },
      { name: 'Bloodhound Knight Darriwil', defeated: false },
      { name: 'Crucible Knight', defeated: false },
      { name: 'Deathbird', defeated: false },
      { name: 'Demi-Human Chief', defeated: false },
      { name: 'Erdtree Burial Watchdog (Stormfoot Catacombs)', defeated: false },
      { name: 'Flying Dragon Agheel', defeated: false },
      { name: 'Godrick the Grafted', defeated: false },
      { name: 'Grafted Scion', defeated: false },
      { name: 'Grave Warden Duelist', defeated: false },
      { name: 'Guardian Golem', defeated: false },
      { name: 'Mad Pumpkin Head', defeated: false },
      { name: 'Margit, the Fell Omen', defeated: false },
      { name: "Night's Cavalry", defeated: false },
      { name: 'Patches', defeated: false },
      { name: 'Soldier of Godrick', defeated: false },
      { name: 'Stonedigger Troll', defeated: false },
      { name: 'Tibia Mariner', defeated: false },
      { name: 'Tree Sentinel', defeated: false },
      { name: 'Ulcerated Tree Spirit', defeated: false },
    ],
  },
  {
    location: 'Liurnia of the Lakes',
    bosses: [
      { name: 'Adan, Thief of Fire', defeated: false },
      { name: 'Alecto, Black Knife Ringleader', defeated: false },
      { name: 'Bell Bearing Hunter', defeated: false },
      { name: 'Black Knife Assassin', defeated: false },
      { name: 'Bloodhound Knight', defeated: false },
      { name: 'Bols, Carian Knight', defeated: false },
      { name: 'Cemetery Shade', defeated: false },
      { name: 'Cleanrot Knight', defeated: false },
      { name: 'Crystalian', defeated: false },
      { name: 'Crystalian Spear & Crystalian Staff (Duo)', defeated: false },
      { name: 'Death Rite Bird', defeated: false },
      { name: 'Deathbird', defeated: false },
      { name: 'Erdtree Avatar (Liurnia Northeast)', defeated: false },
      { name: 'Erdtree Avatar (Liurnia Southwest)', defeated: false },
      { name: 'Erdtree Burial Watchdog', defeated: false },
      { name: 'Glintstone Dragon Adula', defeated: false },
      { name: 'Glintstone Dragon Smarag', defeated: false },
      { name: 'Magma Wyrm Makar', defeated: false },
      { name: "Night's Cavalry (Liurnia North)", defeated: false },
      { name: "Night's Cavalry (Liurnia South)", defeated: false },
      { name: 'Omenkiller', defeated: false },
      { name: 'Onyx Lord', defeated: false },
      { name: 'Red Wolf of Radagon', defeated: false },
      { name: 'Rennala, Queen of the Full Moon', defeated: false },
      { name: 'Royal Knight Loretta', defeated: false },
      { name: 'Royal Revenant', defeated: false },
      { name: 'Spirit-Caller Snail', defeated: false },
      { name: 'Tibia Mariner', defeated: false },
    ],
  },
  {
    location: "Miquella's Haligtree",
    bosses: [
      { name: 'Loretta, Knight of the Haligtree', defeated: false },
      { name: 'Malenia, Blade of Miquella', defeated: false },
    ],
  },
  {
    location: 'Mountaintops of the Giants',
    bosses: [
      { name: 'Ancient Hero of Zamor', defeated: false },
      { name: 'Borealis the Freezing Fog', defeated: false },
      { name: 'Commander Niall', defeated: false },
      { name: 'Death Rite Bird', defeated: false },
      { name: 'Erdtree Avatar', defeated: false },
      { name: 'Fire Giant', defeated: false },
      { name: 'Godskin Apostle and Godskin Noble (Spiritcaller Snail)', defeated: false },
      { name: 'Ulcerated Tree Spirit', defeated: false },
      { name: 'Vyke, Knight of the Roundtable', defeated: false },
    ],
  },
  {
    location: 'Mt. Gelmir',
    bosses: [
      { name: 'Abductor Virgins (Duo)', defeated: false },
      { name: 'Demi-Human Queen Maggie', defeated: false },
      { name: 'Demi-Human Queen Margot', defeated: false },
      { name: 'Full-Grown Fallingstar Beast', defeated: false },
      { name: 'God-Devouring Serpent / Rykard, Lord of Blasphemy', defeated: false },
      { name: 'Godskin Noble', defeated: false },
      { name: 'Kindred of Rot (Duo)', defeated: false },
      { name: 'Magma Wyrm (Fort Laiedd)', defeated: false },
      { name: 'Red Wolf of the Champion', defeated: false },
      { name: 'Ulcerated Tree Spirit', defeated: false },
    ],
  },
  {
    location: 'Nokron, Eternal City',
    bosses: [
      { name: 'Mimic Tear', defeated: false },
      { name: 'Regal Ancestor Spirit', defeated: false },
      { name: 'Valiant Gargoyle & Valiant Gargoyle (Twinblade)', defeated: false },
    ],
  },
  {
    location: 'Rauh Base',
    bosses: [
      { name: 'Death Knight', defeated: false },
      { name: 'Rugalea the Great Red Bear', defeated: false },
    ],
  },
  {
    location: 'Scadu Altus',
    bosses: [
      { name: 'Black Knight Edredd', defeated: false },
      { name: 'Black Knight Garrew', defeated: false },
      { name: 'Count Ymir, Mother of Fingers', defeated: false },
      { name: 'Curseblade Labirith', defeated: false },
      { name: 'Death Knight', defeated: false },
      { name: 'Dryleaf Dane', defeated: false },
      { name: 'Ghostflame Dragon', defeated: false },
      { name: 'Golden Hippopotamus', defeated: false },
      { name: 'Messmer the Impaler + Base Serpent Messmer', defeated: false },
      { name: 'Metyr, Mother of Fingers', defeated: false },
      { name: 'Rakshasa', defeated: false },
      { name: 'Jori, Elder Inquisitor', defeated: false },
      { name: 'Ralva the Great Red Bear', defeated: false },
      { name: 'Tree Sentinel', defeated: false },
    ],
  },
  {
    location: 'Scaduview',
    bosses: [
      { name: 'Fallingstar Beast', defeated: false },
      { name: 'Scadutree Avatar', defeated: false },
      { name: 'Commander Gaius', defeated: false },
      { name: 'Tree Sentinel', defeated: false },
    ],
  },
  {
    location: 'Siofra River',
    bosses: [
      { name: 'Ancestor Spirit', defeated: false },
      { name: 'Dragonkin Soldier', defeated: false },
      { name: 'Mohg, Lord of Blood', defeated: false },
    ],
  },
  {
    location: 'Weeping Peninsula',
    bosses: [
      { name: 'Ancient Hero of Zamor', defeated: false },
      { name: 'Cemetery Shade', defeated: false },
      { name: 'Deathbird', defeated: false },
      { name: 'Erdtree Avatar', defeated: false },
      { name: "Erdtree Burial Watchdog (Impaler's Catacombs)", defeated: false },
      { name: 'Leonine Misbegotten', defeated: false },
      { name: 'Miranda the Blighted Bloom', defeated: false },
      { name: "Night's Cavalry", defeated: false },
      { name: 'Runebear', defeated: false },
      { name: 'Scaly Misbegotten', defeated: false },
    ],
  },
]
