export interface Boss {
  name: string
  location: string
  defeated: boolean
}

export const Bosses: Boss[] = [
  {
    name: 'Midra Lord of Frenzied Flame',
    location: 'Abyssal Woods',
    defeated: false,
  },
  {
    name: 'Dragonkin Soldier of Nokstella',
    location: 'Ainsel River',
    defeated: false,
  },
  {
    name: 'Ancient Dragon Lansseax',
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: 'Ancient Hero of Zamor',
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: "Black Knife Assassin (Sage's Cave)",
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: "Black Knife Assassin (Sainted Hero's Grave)",
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: 'Crystalian Spear & Crystalian Ringblade',
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: 'Demi-Human Queen Gilika',
    location: 'Altus Plateau',
    defeated: false,
  },
  { name: 'Elemer of the Briar', location: 'Altus Plateau', defeated: false },
  {
    name: 'Erdtree Burial Watchdog',
    location: 'Altus Plateau',
    defeated: false,
  },
  { name: 'Fallingstar Beast', location: 'Altus Plateau', defeated: false },
  {
    name: 'Godefroy The Grafted',
    location: 'Altus Plateau',
    defeated: false,
  },
  { name: 'Godskin Apostle', location: 'Altus Plateau', defeated: false },
  { name: 'Necromancer Garris', location: 'Altus Plateau', defeated: false },
  { name: "Night's Cavalry", location: 'Altus Plateau', defeated: false },
  {
    name: 'Omenkiller & Miranda the Blighted Bloom',
    location: 'Altus Plateau',
    defeated: false,
  },
  {
    name: 'Perfumer Tricia & Misbegotten Warrior',
    location: 'Altus Plateau',
    defeated: false,
  },
  { name: 'Sanguine Noble', location: 'Altus Plateau', defeated: false },
  { name: 'Stonedigger Troll', location: 'Altus Plateau', defeated: false },
  { name: 'Tibia Mariner', location: 'Altus Plateau', defeated: false },
  { name: 'Tree Sentinel (Duo)', location: 'Altus Plateau', defeated: false },
  { name: 'Wormface', location: 'Altus Plateau', defeated: false },
  {
    name: 'Divine Beast Dancing Lion',
    location: 'Ancient Ruins of Rauh',
    defeated: false,
  },
  {
    name: 'Romina, Saint of the Bud',
    location: 'Ancient Ruins of Rauh',
    defeated: false,
  },
  { name: 'Cemetery Shade', location: 'Caelid', defeated: false },
  { name: "Commander O'Neil", location: 'Caelid', defeated: false },
  {
    name: 'Crucible Knight & Misbegotten Warrior',
    location: 'Caelid',
    defeated: false,
  },
  { name: 'Death Rite Bird', location: 'Caelid', defeated: false },
  { name: 'Decaying Ekzykes', location: 'Caelid', defeated: false },
  {
    name: 'Erdtree Burial Watchdog (Duo)',
    location: 'Caelid',
    defeated: false,
  },
  { name: 'Fallingstar Beast', location: 'Caelid', defeated: false },
  { name: 'Frenzied Duelist', location: 'Caelid', defeated: false },
  { name: 'Mad Pumpkin Heads', location: 'Caelid', defeated: false },
  { name: 'Magma Wyrm', location: 'Caelid', defeated: false },
  { name: "Night's Cavalry (Caelid)", location: 'Caelid', defeated: false },
  {
    name: 'Nox Swordstress & Nox Priest',
    location: 'Caelid',
    defeated: false,
  },
  { name: 'Putrid Avatar', location: 'Caelid', defeated: false },
  { name: 'Starscourge Radahn', location: 'Caelid', defeated: false },
  {
    name: 'Bell Bearing Hunter',
    location: 'Capital Outskirts',
    defeated: false,
  },
  {
    name: 'Crucible Knight & Crucible Knight Ordovis',
    location: 'Capital Outskirts',
    defeated: false,
  },
  { name: 'Deathbird', location: 'Capital Outskirts', defeated: false },
  {
    name: 'Draconic Tree Sentinel',
    location: 'Capital Outskirts',
    defeated: false,
  },
  { name: 'Fell Twins', location: 'Capital Outskirts', defeated: false },
  {
    name: 'Grave Warden Duelist',
    location: 'Capital Outskirts',
    defeated: false,
  },
  { name: 'Onyx Lord', location: 'Capital Outskirts', defeated: false },
  { name: 'Dancer of Ranah', location: 'Cerulean Coast', defeated: false },
  {
    name: 'Demi-Human Queen Marigga',
    location: 'Cerulean Coast',
    defeated: false,
  },
  { name: 'Ghostflame Dragon', location: 'Cerulean Coast', defeated: false },
  { name: 'Putrescent Knight', location: 'Cerulean Coast', defeated: false },
  {
    name: 'Death Rite Bird',
    location: "Charo's Hidden Grave",
    defeated: false,
  },
  { name: 'Lamenter', location: "Charo's Hidden Grave", defeated: false },
  {
    name: 'Tibia Mariner',
    location: "Charo's Hidden Grave",
    defeated: false,
  },
  {
    name: 'Astel, Stars of Darkness',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Death Rite Bird',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Great Wyrm Theodorix',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Misbegotten Crusader',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: "Night's Cavalry (Duo)",
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Putrid Avatar',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Putrid Grave Warden Duelist',
    location: 'Consecrated Snowfield',
    defeated: false,
  },
  {
    name: 'Beast Clergyman / Maliketh, the Black Blade',
    location: 'Crumbling Farum Azula',
    defeated: false,
  },
  {
    name: 'Dragonlord Placidusax',
    location: 'Crumbling Farum Azula',
    defeated: false,
  },
  { name: 'Godskin Duo', location: 'Crumbling Farum Azula', defeated: false },
  {
    name: 'Crucible Knight Siluria',
    location: 'Deeproot Depths',
    defeated: false,
  },
  { name: "Fia's Champions", location: 'Deeproot Depths', defeated: false },
  {
    name: 'Lichdragon Fortissax',
    location: 'Deeproot Depths',
    defeated: false,
  },
  { name: 'Battlemage Hugues', location: 'Dragonbarrow', defeated: false },
  {
    name: 'Beastman of Farum Azula (Duo)',
    location: 'Dragonbarrow',
    defeated: false,
  },
  { name: 'Bell Bearing Hunter', location: 'Dragonbarrow', defeated: false },
  { name: 'Black Blade Kindred ', location: 'Dragonbarrow', defeated: false },
  {
    name: 'Cleanrot Knight (Duo)',
    location: 'Dragonbarrow',
    defeated: false,
  },
  { name: 'Flying Dragon Greyll', location: 'Dragonbarrow', defeated: false },
  { name: 'Godskin Apostle', location: 'Dragonbarrow', defeated: false },
  {
    name: "Night's Cavalry (Dragonbarrow)",
    location: 'Dragonbarrow',
    defeated: false,
  },
  { name: 'Putrid Avatar', location: 'Dragonbarrow', defeated: false },
  {
    name: 'Putrid Crystalian Trio',
    location: 'Dragonbarrow',
    defeated: false,
  },
  { name: 'Putrid Tree Spirit', location: 'Dragonbarrow', defeated: false },
  {
    name: 'Radagon of the Golden Order / Elden Beast',
    location: 'Elden Throne',
    defeated: false,
  },
  {
    name: 'Promised Consort Radahn + Radahn Consort of Miquella',
    location: 'Enir-Ilim',
    defeated: false,
  },
  {
    name: 'Black Blade Kindred',
    location: 'Forbidden Lands',
    defeated: false,
  },
  { name: "Night's Cavalry", location: 'Forbidden Lands', defeated: false },
  { name: 'Stray Mimic Tear', location: 'Forbidden Lands', defeated: false },
  { name: 'Blackgaol Knight', location: 'Gravesite Plain', defeated: false },
  { name: 'Chief Bloodfiend', location: 'Gravesite Plain', defeated: false },
  {
    name: 'Demi-Human Swordmaster Onze',
    location: 'Gravesite Plain',
    defeated: false,
  },
  {
    name: 'Divine Beast Dancing Lion',
    location: 'Gravesite Plain',
    defeated: false,
  },
  { name: 'Ghostflame Dragon', location: 'Gravesite Plain', defeated: false },
  { name: 'Red Bear', location: 'Gravesite Plain', defeated: false },
  {
    name: 'Rellana Twin Moon Knight',
    location: 'Gravesite Plain',
    defeated: false,
  },
  {
    name: 'Ancient Dragon Senessax',
    location: 'Jagged Peak',
    defeated: false,
  },
  { name: 'Ancient Dragon-Man', location: 'Jagged Peak', defeated: false },
  { name: 'Bayle the Dread', location: 'Jagged Peak', defeated: false },
  { name: 'Jagged Peak Drake x2', location: 'Jagged Peak', defeated: false },
  {
    name: 'Astel, Naturalborn of the Void',
    location: 'Lake of Rot',
    defeated: false,
  },
  { name: 'Dragonkin Soldier', location: 'Lake of Rot', defeated: false },
  {
    name: 'Godfrey, First Elden Lord (Hoarah Loux)',
    location: 'Leyndell, Ashen Capital',
    defeated: false,
  },
  {
    name: 'Sir Gideon Ofnir, the All-Knowing',
    location: 'Leyndell, Ashen Capital',
    defeated: false,
  },
  {
    name: 'Esgar, Priest of Blood',
    location: 'Leyndell, Royal Capital',
    defeated: false,
  },
  {
    name: 'Godfrey, First Elden Lord',
    location: 'Leyndell, Royal Capital',
    defeated: false,
  },
  {
    name: 'Mohg, the Omen',
    location: 'Leyndell, Royal Capital',
    defeated: false,
  },
  {
    name: 'Morgott, the Omen King',
    location: 'Leyndell, Royal Capital',
    defeated: false,
  },
  { name: 'Beastman of Farum Azula', location: 'Limgrave', defeated: false },
  { name: 'Bell Bearing Hunter', location: 'Limgrave', defeated: false },
  { name: 'Black Knife Assassin', location: 'Limgrave', defeated: false },
  {
    name: 'Bloodhound Knight Darriwil',
    location: 'Limgrave',
    defeated: false,
  },
  { name: 'Crucible Knight', location: 'Limgrave', defeated: false },
  { name: 'Deathbird', location: 'Limgrave', defeated: false },
  { name: 'Demi-Human Chief', location: 'Limgrave', defeated: false },
  {
    name: 'Erdtree Burial Watchdog (Stormfoot Catacombs)',
    location: 'Limgrave',
    defeated: false,
  },
  { name: 'Flying Dragon Agheel', location: 'Limgrave', defeated: false },
  { name: 'Godrick the Grafted', location: 'Limgrave', defeated: false },
  { name: 'Grafted Scion', location: 'Limgrave', defeated: false },
  { name: 'Grave Warden Duelist', location: 'Limgrave', defeated: false },
  { name: 'Guardian Golem', location: 'Limgrave', defeated: false },
  { name: 'Mad Pumpkin Head', location: 'Limgrave', defeated: false },
  { name: 'Margit, the Fell Omen', location: 'Limgrave', defeated: false },
  { name: "Night's Cavalry", location: 'Limgrave', defeated: false },
  { name: 'Patches', location: 'Limgrave', defeated: false },
  { name: 'Soldier of Godrick', location: 'Limgrave', defeated: false },
  { name: 'Stonedigger Troll', location: 'Limgrave', defeated: false },
  { name: 'Tibia Mariner', location: 'Limgrave', defeated: false },
  { name: 'Tree Sentinel', location: 'Limgrave', defeated: false },
  { name: 'Ulcerated Tree Spirit', location: 'Limgrave', defeated: false },
  {
    name: 'Adan, Thief of Fire',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Alecto, Black Knife Ringleader',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Bell Bearing Hunter',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Black Knife Assassin',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Bloodhound Knight',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Bols, Carian Knight',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Cemetery Shade',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Cleanrot Knight',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  { name: 'Crystalian', location: 'Liurnia of the Lakes', defeated: false },
  {
    name: 'Crystalian Spear & Crystalian Staff (Duo)',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Death Rite Bird',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  { name: 'Deathbird', location: 'Liurnia of the Lakes', defeated: false },
  {
    name: 'Erdtree Avatar (Liurnia Northeast)',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Erdtree Avatar (Liurnia Southwest)',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Erdtree Burial Watchdog',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Glintstone Dragon Adula',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Glintstone Dragon Smarag',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Magma Wyrm Makar',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: "Night's Cavalry (Liurnia North)",
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: "Night's Cavalry (Liurnia South)",
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  { name: 'Omenkiller', location: 'Liurnia of the Lakes', defeated: false },
  { name: 'Onyx Lord', location: 'Liurnia of the Lakes', defeated: false },
  {
    name: 'Red Wolf of Radagon',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Rennala, Queen of the Full Moon',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Royal Knight Loretta',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Royal Revenant',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Spirit-Caller Snail',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Tibia Mariner',
    location: 'Liurnia of the Lakes',
    defeated: false,
  },
  {
    name: 'Loretta, Knight of the Haligtree',
    location: "Miquella's Haligtree",
    defeated: false,
  },
  {
    name: 'Malenia, Blade of Miquella',
    location: "Miquella's Haligtree",
    defeated: false,
  },
  {
    name: 'Ancient Hero of Zamor',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Borealis the Freezing Fog',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Commander Niall',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Death Rite Bird',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Erdtree Avatar',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Fire Giant',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Godskin Apostle and Godskin Noble (Spiritcaller Snail)',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Ulcerated Tree Spirit',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  {
    name: 'Vyke, Knight of the Roundtable',
    location: 'Mountaintops of the Giants',
    defeated: false,
  },
  { name: 'Abductor Virgins (Duo)', location: 'Mt. Gelmir', defeated: false },
  {
    name: 'Demi-Human Queen Maggie',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  {
    name: 'Demi-Human Queen Margot',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  {
    name: 'Full-Grown Fallingstar Beast',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  {
    name: 'God-Devouring Serpent / Rykard, Lord of Blasphemy',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  { name: 'Godskin Noble', location: 'Mt. Gelmir', defeated: false },
  { name: 'Kindred of Rot (Duo)', location: 'Mt. Gelmir', defeated: false },
  {
    name: 'Magma Wyrm (Fort Laiedd)',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  {
    name: 'Red Wolf of the Champion',
    location: 'Mt. Gelmir',
    defeated: false,
  },
  { name: 'Ulcerated Tree Spirit', location: 'Mt. Gelmir', defeated: false },
  { name: 'Mimic Tear', location: 'Nokron, Eternal City', defeated: false },
  {
    name: 'Regal Ancestor Spirit',
    location: 'Nokron, Eternal City',
    defeated: false,
  },
  {
    name: 'Valiant Gargoyle & Valiant Gargoyle (Twinblade)',
    location: 'Nokron, Eternal City',
    defeated: false,
  },
  { name: 'Death Knight', location: 'Rauh Base', defeated: false },
  {
    name: 'Rugalea the Great Red Bear',
    location: 'Rauh Base',
    defeated: false,
  },
  { name: 'Black Knight Edredd', location: 'Scadu Altus', defeated: false },
  { name: 'Black Knight Garrew', location: 'Scadu Altus', defeated: false },
  {
    name: 'Count Ymir, Mother of Fingers',
    location: 'Scadu Altus',
    defeated: false,
  },
  { name: 'Curseblade Labirith', location: 'Scadu Altus', defeated: false },
  { name: 'Death Knight', location: 'Scadu Altus', defeated: false },
  { name: 'Dryleaf Dane', location: 'Scadu Altus', defeated: false },
  { name: 'Ghostflame Dragon', location: 'Scadu Altus', defeated: false },
  { name: 'Golden Hippopotamus', location: 'Scadu Altus', defeated: false },
  {
    name: 'Jori, Elder Inquisitor',
    location: 'Scadu Altus',
    defeated: false,
  },
  {
    name: 'Messmer the Impaler + Base Serpent Messmer',
    location: 'Scadu Altus',
    defeated: false,
  },
  {
    name: 'Metyr, Mother of Fingers',
    location: 'Scadu Altus',
    defeated: false,
  },
  { name: 'Rakshasa', location: 'Scadu Altus', defeated: false },
  {
    name: 'Ralva the Great Red Bear',
    location: 'Scadu Altus',
    defeated: false,
  },
  { name: 'Tree Sentinel', location: 'Scadu Altus', defeated: false },
  { name: 'Commander Gaius', location: 'Scaduview', defeated: false },
  { name: 'Fallingstar Beast', location: 'Scaduview', defeated: false },
  { name: 'Scadutree Avatar', location: 'Scaduview', defeated: false },
  { name: 'Tree Sentinel', location: 'Scaduview', defeated: false },
  { name: 'Ancestor Spirit', location: 'Siofra River', defeated: false },
  { name: 'Dragonkin Soldier', location: 'Siofra River', defeated: false },
  { name: 'Mohg, Lord of Blood', location: 'Siofra River', defeated: false },
  {
    name: 'Ancient Hero of Zamor',
    location: 'Weeping Peninsula',
    defeated: false,
  },
  { name: 'Cemetery Shade', location: 'Weeping Peninsula', defeated: false },
  { name: 'Deathbird', location: 'Weeping Peninsula', defeated: false },
  { name: 'Erdtree Avatar', location: 'Weeping Peninsula', defeated: false },
  {
    name: "Erdtree Burial Watchdog (Impaler's Catacombs)",
    location: 'Weeping Peninsula',
    defeated: false,
  },
  {
    name: 'Leonine Misbegotten',
    location: 'Weeping Peninsula',
    defeated: false,
  },
  {
    name: 'Miranda the Blighted Bloom',
    location: 'Weeping Peninsula',
    defeated: false,
  },
  { name: "Night's Cavalry", location: 'Weeping Peninsula', defeated: false },
  { name: 'Runebear', location: 'Weeping Peninsula', defeated: false },
  {
    name: 'Scaly Misbegotten',
    location: 'Weeping Peninsula',
    defeated: false,
  },
]
